#!/usr/bin/perl -w

use esmith::Build::CreateLinks qw(:all);
my $event = 'nethvoice-wizard-restapi-update';

event_actions($event, qw(
    initialize-default-databases 00
    nethvoice-wizard-restapi-update 60
));

event_templates($event, qw(
    /var/www/html/freepbx/rest/config.inc.php
));
