#!/usr/bin/expect
# usage: ./mediatrix-tftp <GATEWAY IP> <TFTP-IP> <CONFIGURATION FILENAME> <USERNAME> <PASSWORD>

set gatewayip [lindex $argv 0]
set tftpip [lindex $argv 1]
set filename [lindex $argv 2]
set username [lindex $argv 3]
set password [lindex $argv 4]

spawn  /usr/bin/ssh -o "StrictHostKeyChecking=no" $username@$gatewayip
expect "password:"
send "$password\r"
expect "Global>"
send "Conf.ScriptSpecificFileName =$filename\r"
expect "Global>"
send "Conf.ScriptGenericFileName =$filename\r"
expect "Global>"
send "Conf.ScriptsLocation =\"\"\r"
expect "Global>"
send "Conf.ScriptsTransferProtocol =\"tftp\"\r"
expect "Global>"
send "Conf.ScriptsTransferSrvHostname =\"$tftpip\"\r"
send "Conf.ScriptsAllowRepeatedExecution =Disable\r"
send "Conf.ScriptsTransferOnRestartEnable =Enable\r"
send "reboot\r"
expect eof

