#!/usr/bin/expect
# usage: ./sangoma-tftp <GATEWAY IP> <TFTP-IP> <CONFIGURATION FILENAME> <USERNAME> <PASSWORD>

set gatewayip [lindex $argv 0]
set tftpip [lindex $argv 1]
set filename [lindex $argv 2]
set username [lindex $argv 3]
set password [lindex $argv 4]

spawn /usr/bin/telnet $gatewayip
expect "Username:"
send "$username\r"
expect "Password:"
send "$password\r"
expect ">"
send "GET tftp://$tftpip/$filename\r"
expect "admin  >"
send "SAVE\r"
expect "admin  >"
send "REBOOT SYSTEM BLOCK\r"
expect "admin  >"
expect eof

