#!/usr/bin/expect
# usage: ./trinity-tftp <GATEWAY IP> <TFTP-IP> <CONFIGURATION FILENAME> <USERNAME> <PASSWORD>

set gatewayip [lindex $argv 0]
set tftpip [lindex $argv 1]
set filename [lindex $argv 2]
set username [lindex $argv 3]
set password [lindex $argv 4]

spawn /usr/bin/telnet $gatewayip
expect "login:"
send "$username\r"
expect "Password:"
send "$password\r"
expect ">"
send "enable\r"
expect "#"
send "copy tftp://$tftpip/$filename config:tmp-config\r"
expect "#"
send "copy config:tmp-config startup-config\r"
expect "#"
send "reload\r"
expect "#"
send "yes\r"
expect eof

