#!/bin/bash
mysql_password=$(perl -mNethServer::Password -e "print NethServer::Password::store('mysql')")

# Create rest module sql tables
for i in $(ls /var/www/html/freepbx/rest/sql/*.sql); do
    mysql -uroot -p$mysql_password asterisk < ${i}
done

# Create default profile permissions only if it is needed
if [[ $(/usr/bin/mysql -B -N -uroot -p$mysql_password asterisk -e "SELECT COUNT(*) FROM rest_cti_profiles") == 0 ]] ; then
    /usr/bin/mysql -uroot -p$mysql_password asterisk < /var/www/html/freepbx/rest/sql/cti_default_permissions/cti_permissions.sql
fi

# Add column if not present
EXISTS=$(/usr/bin/mysql -uroot -p$mysql_password -se "SHOW COLUMNS FROM asterisk.rest_cti_profiles_paramurl LIKE 'only_queues'");
if [[ $EXISTS == "" ]]; then
    $(/usr/bin/mysql -uroot -p$mysql_password -e "ALTER TABLE asterisk.rest_cti_profiles_paramurl ADD COLUMN only_queues TINYINT(1) NOT NULL DEFAULT 0");
fi
