#!/bin/bash
mysql_password=$(perl -mNethServer::Password -e "print NethServer::Password::store('mysql')")

# Create rest module sql tables
for i in $(ls /var/www/html/freepbx/rest/sql/*.sql); do
    mysql -uroot -p$mysql_password asterisk < ${i}
done

# Create default profile permissions only if it is needed
if [[ $(/usr/bin/mysql -B -N -uroot -p$mysql_password asterisk -e "SELECT COUNT(*) FROM rest_cti_profiles") == 0 ]] ; then
    /usr/bin/mysql -uroot -p$mysql_password asterisk < /var/www/html/freepbx/rest/sql/cti_default_permissions/cti_permissions.sql
fi

# Create custom context for CTI profiles and add extension to them
/usr/bin/scl enable rh-php56 -- php /var/www/html/freepbx/rest/lib/contextMigrationHelper.php
