USE asterisk;
DROP TABLE IF EXISTS `providers`;
CREATE TABLE `providers` (
  `provider` varchar(100) NOT NULL DEFAULT '',
  `description` varchar(100) NOT NULL DEFAULT '',
  `dettpeer` mediumtext NOT NULL,
  `dettuser` varchar(250) DEFAULT NULL,
  `registration` varchar(250) DEFAULT NULL,
  PRIMARY KEY (`provider`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

LOCK TABLES `providers` WRITE;
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('clouditalia','Clouditalia','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=voip.eutelia.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.eutelia.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@voip.eutelia.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('messagenet','MessageNet','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.messagenet.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.messagenet.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@sip.messagenet.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('voipvoice','VoipVoice','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=link.voipvoice.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=link.voipvoice.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@link.voipvoice.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('cheapnet','Cheapnet','disallow=all\nallow=CODECS\ndtmfmode=rfc2833\nfromdomain=sip.cheapnet.it\nhost=sip.cheapnet.it\nqualify=yes\nsecret=PASSWORD\ntype=friend\nnat=yes\nusername=USERNAME\ncanreinvite=no\ncontext=from-pstn\nsendrpid=no\ninsecure=port,invite','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@sip.cheapnet.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('opensolution_sip','Opensolution Sip','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nfromdomain=sip.opensolution.it\nhost=sip.opensolution.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.opensolution.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@sip.opensolution.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('opensolution_voip','Opensolution Voip','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nfromdomain=voip.opensolution.it\nhost=voip.opensolution.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=voip.opensolution.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@voip.opensolution.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('sixcomm','Six Comm','username=USERNAME\ntype=friend\nsecret=PASSWORD\nqualify=yes\ninsecure=port,invite\nhost=voip.sixcomm.net\ndtmfmode=rfc2833\nallow=CODECS','type=USERNAME\nsecret=PASSWORD\ninsecure=port,invite\ncontext=from-trunk\ndtmfmode=rfc2833\nallow=CODECS','USERNAME@voip.sixcomm.net:PASSWORD:USERNAME@pcscf.sixcomm.net/USERNAME');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('twt','TWT','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=NUMERO\nhost=res.sip.twt.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=res.sip.twt.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME\nfromdomain=res.sip.twt.it','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@res.sip.twt.it/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('xstream','XSTREAM','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=128.65.200.18\ninsecure=invite\nnat=yes\nport=5083\nqualify=yes\nrealm=xstreamtest.site\nsecret=PASSWORD\nsrvlookup=yes\ntype=peer\nusername=USERNAME\nfromdomain=xstreamtest.site','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','NUMERO@xstreamtest.site:PASSWORD@128.65.200.18:5083/NUMERO');
INSERT IGNORE INTO `providers` (`provider`, `description`, `dettpeer`, `dettuser`, `registration`) VALUES ('voipeasy','VoipEasy','disallow=all\nallow=CODECS\nbindaddr=0.0.0.0\ncanreinvite=yes\ndefaultexpirey=330\ndtmfmode=rfc2833\nfromuser=USERNAME\nhost=sip.voipeasy.it\ninsecure=very\nnat=yes\nport=5060\nqualify=yes\nrealm=sip.voipeasy.it\nsecret=PASSWORD\nsrvlookup=yes\ntype=friend\nuseragent=Asterisk_Eut\nusername=USERNAME','allow=CODECS\ncontext=from-pstn\nsecret=PASSWORD\ntype=user\ndtmfmode=rfc2833','USERNAME:PASSWORD@sip.voipeasy.it/NUMERO');
UNLOCK TABLES;

